appName: "클라우드"
awsEc2: false
runCycleSec: 1
sameKeywordThreasholdSec: 30
sameKeywordExtractLen: 20
filelist:
  - id: application
    path: /Users/jungwoopark/workspace/refrence/source/GO/frjufvjn/logmonitor/test.log
    keywords:
      - pattern: ERROR
      - pattern: WARN
alarm:
  slack:
    enable: true
    incommingWebhookUrl: "https://dddd"
  jandi:
    enable: false
    incommingWebhookUrl: "https://wh.jandi.com/connect-api/webhook/999999999/xxxxxxxxxxxxxxxxxxxxxx"